CREATE DATABASE BH
DROP TABLE S
CREATE TABLE S
( S# CHAR(2), SNAME CHAR(15), CITY CHAR(10), STATUS INT)

INSERT INTO S VALUES 
('S1', 'Thanh Huong', 'HCM', 2000),
('S2', 'Lan Chien', 'HCM', 1000)

SELECT * FROM S;

